<?php

$group = 'Addtional Options';
vc_map( array(
	'base'          => 'goso_media_carousel',
	'icon'          => get_template_directory_uri() . '/images/vc-icon.png',
	'category'      => goso_get_theme_name('Authow'),
	'html_template' => get_template_directory() . '/inc/js_composer/shortcodes/media_carousel/frontend.php',
	'weight'        => 700,
	'as_parent'     => array( 'except' => 'goso_media_carousel' ),
	'name'          => goso_get_theme_name('Goso').' '.esc_html__( 'Advanced Carousel', 'authow' ),
	'description'   => __( 'Media Advanced Block', 'authow' ),
	'controls'      => 'full',
	'params'        => array(
		array(
			'type'             => 'goso_only_number',
			'heading'          => esc_html__( 'Gap', 'goso-framework' ),
			'param_name'       => 'slides_item_gap',
			'class'            => '',
			'value'            => 10,
			'min'              => 1,
			'max'              => 100,
			'step'             => 1,
		),
		array(
			'type'       => 'goso_only_number',
			'heading'    => esc_html__( 'On desktop', 'goso-framework' ),
			'param_name' => 'limit_desk',
			'class'      => '',
			'value'      => 3,
			'min'        => 1,
			'max'        => 25,
			'step'       => 1,
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'       => 'goso_only_number',
			'heading'    => esc_html__( 'On tab', 'goso-framework' ),
			'param_name' => 'limit_tab',
			'class'      => '',
			'value'      => 2,
			'min'        => 1,
			'max'        => 25,
			'step'       => 1,
			'edit_field_class' => 'vc_col-sm-4',
		),
		array(
			'type'       => 'goso_only_number',
			'heading'    => esc_html__( 'On mobile', 'goso-framework' ),
			'param_name' => 'limit_mobile',
			'class'      => '',
			'value'      => 1,
			'min'        => 1,
			'max'        => 25,
			'step'       => 1,
			'edit_field_class' => 'vc_col-sm-4',
		),
		// Slider
		array(
			'type'       => 'checkbox',
			'heading'    => esc_html__( 'Autoplay', 'authow' ),
			'param_name' => 'autoplay',
			'value'      => array( esc_html__( 'Yes', 'authow' ) => 'yes' ),
			'std'        => 'yes',
			'group'      => $group,
		),
		array(
			'type'       => 'checkbox',
			'heading'    => esc_html__( 'Slider Loop', 'authow' ),
			'param_name' => 'loop',
			'value'      => array( esc_html__( 'Yes', 'authow' ) => 'yes' ),
			'std'        => 'yes',
			'group'      => $group,
		),
		array(
			'type'       => 'textfield',
			'param_name' => 'auto_time',
			'heading'    => esc_html__( 'Slider Auto Time (at x seconds)', 'authow' ),
			'value'      => 4000,
			'group'      => $group,
		),
		array(
			'type'       => 'textfield',
			'param_name' => 'speed',
			'heading'    => esc_html__( 'Slider Speed (at x seconds)', 'authow' ),
			'value'      => 800,
			'group'      => $group,
		),
		array(
			'type'       => 'checkbox',
			'heading'    => esc_html__( 'Show next/prev buttons', 'authow' ),
			'param_name' => 'shownav',
			'value'      => array( esc_html__( 'Yes', 'authow' ) => 'yes' ),
			'std'        => 'yes',
			'group'      => $group,
		),
		array(
			'type'       => 'checkbox',
			'heading'    => esc_html__( 'Show dots navigation', 'authow' ),
			'param_name' => 'showdots',
			'value'      => array( esc_html__( 'Yes', 'authow' ) => 'yes' ),
			'group'      => $group,
		)
	),
	'js_view'                 => 'VcColumnView'
) );
