<?php
$group_icon  = 'Icon';
$group_line  = 'Line';
$group_color = 'Typo & Color';

vc_map( array(
	'base'          => "goso_info_box",
	'icon'          => get_template_directory_uri() . '/images/vc-icon.png',
	'category'      => goso_get_theme_name('Authow'),
	'html_template' => get_template_directory() . '/inc/js_composer/shortcodes/info_box/frontend.php',
	'weight'        => 700,
	'name'          => goso_get_theme_name('Goso').' '.__( 'Info Box', 'authow' ),
	'description'   => __( 'Info Box Block', 'authow' ),
	'controls'      => 'full',
	'params'        => array(
		array(
			'type'       => 'textfield',
			'heading'    => esc_html__( 'Sub Title', 'authow' ),
			'param_name' => 'subtitle',
		),
		array(
			'type'       => 'textfield',
			'heading'    => esc_html__( 'Title', 'authow' ),
			'param_name' => 'title_text',
		),
		array(
			'type'       => 'checkbox',
			'heading'    => __( 'Use line below the title', 'authow' ),
			'param_name' => '_use_line',
		),
		array(
			'type'       => 'textarea',
			'heading'    => esc_html__( 'Content', 'authow' ),
			'param_name' => 'description_text',
			'value'      => esc_html__( 'Insert your content here', 'authow' )
		),
		array(
			'type'       => 'dropdown',
			'heading'    => esc_html__( 'Icon position', 'authow' ),
			'param_name' => 'icon_position',
			'value'      => array(
				esc_html__( 'Top left', 'authow' )    => 'top-left',
				esc_html__( 'Top center', 'authow' )  => 'top-center',
				esc_html__( 'Top right', 'authow' )   => 'top-right',
				esc_html__( 'Float left', 'authow' )  => 'float-left',
				esc_html__( 'Float right', 'authow' ) => 'float-right'
			),
			'std'        => 'float-left',
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'stitle_mar_top',
			'heading'          => __( 'Custom Margin Top for Sub Title', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'title_mar_top',
			'heading'          => __( 'Custom Margin Top for Title', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'title_mar_bottom',
			'heading'          => __( 'Custom Margin Bottom for Title', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'       => 'goso_number',
			'param_name' => 'des_mar_top',
			'heading'    => __( 'Custom Margin Top for Description', 'authow' ),
			'value'      => '',
			'std'        => '',
			'suffix'     => 'px',
			'min'        => 1,
		),

		array(
			'type'       => 'dropdown',
			'heading'    => esc_html__( 'Icon type', 'authow' ),
			'param_name' => 'icon_type',
			'value'      => array(
				esc_html__( 'Icon', 'authow' )  => 'icon',
				esc_html__( 'Image', 'authow' ) => 'image',
				esc_html__( 'Text', 'authow' ) => 'text',
			),
			'group'      => 'Icon & Image'
		),
		array(
			'type'             => 'attach_image',
			'heading'          => esc_html__( 'Image', 'authow' ),
			'param_name'       => 'image',
			'dependency'       => array( 'element' => 'icon_type', 'value' => 'image' ),
			'edit_field_class' => 'vc_col-sm-6',
			'group'            => 'Icon & Image'
		),
		array(
			'type'             => 'attach_image',
			'heading'          => esc_html__( 'Image hover', 'authow' ),
			'param_name'       => 'image_hover',
			'dependency'       => array( 'element' => 'icon_type', 'value' => 'image' ),
			'group'            => 'Icon & Image',
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'        => 'iconpicker',
			'heading'     => __( 'Icon', 'authow' ),
			'param_name'  => 'icon_fontawesome',
			'value'       => 'fa fa-adjust',
			'settings'    => array( 'emptyIcon' => false, 'iconsPerPage' => 100 ),
			'description' => __( 'Select icon from library.', 'authow' ),
			'dependency'  => array( 'element' => 'icon_type', 'value' => 'icon' ),
			'group'       => 'Icon & Image'
		),
		array(
			'type'       => 'textfield',
			'heading'    => esc_html__( 'Icon Text', 'authow' ),
			'value'    => esc_html__( '02', 'authow' ),
			'dependency'  => array( 'element' => 'icon_type', 'value' => 'text' ),
			'param_name' => 'icontext',
			'group'       => 'Icon & Image'
		),
		array(
			'type'             => 'dropdown',
			'heading'          => esc_html__( 'View', 'authow' ),
			'param_name'       => 'icon_view',
			'value'            => array(
				esc_html__( 'Default', 'authow' ) => 'default',
				esc_html__( 'Stacked', 'authow' ) => 'stacked',
				esc_html__( 'Framed', 'authow' )  => 'framed',
			),
			'group'            => 'Icon & Image',
			'dependency'       => array( 'element' => 'icon_type', 'value' => array( 'icon', 'text' ) ),
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'dropdown',
			'heading'          => esc_html__( 'Shape', 'authow' ),
			'param_name'       => 'icon_shape',
			'value'            => array(
				esc_html__( 'Circle', 'authow' ) => 'circle',
				esc_html__( 'Square', 'authow' ) => 'square'
			),
			'group'            => 'Icon & Image',
			'dependency'       => array( 'element' => 'icon_view', 'value_not_equal_to' => 'default' ),
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'       => 'dropdown',
			'heading'    => esc_html__( 'Hover Animation', 'authow' ),
			'param_name' => 'icon_hover_animation',
			'value'      => array(
				esc_html__( 'None', 'authow' )                   => '',
				esc_html__( 'Grow', 'authow' )                   => 'grow',
				esc_html__( 'Shrink', 'authow' )                 => 'shrink',
				esc_html__( 'Pulse', 'authow' )                  => 'pulse',
				esc_html__( 'Pulse Grow', 'authow' )             => 'pulse-grow',
				esc_html__( 'Pulse Shrink', 'authow' )           => 'pulse-shrink',
				esc_html__( 'Push', 'authow' )                   => 'push',
				esc_html__( 'Pop', 'authow' )                    => 'pop',
				esc_html__( 'Custom Style 1', 'authow' ) => 'custom-1',
				esc_html__( 'Custom Style 2', 'authow' ) => 'custom-2',
				esc_html__( 'Custom Style 3', 'authow' ) => 'custom-3',
				esc_html__( 'Custom Style 4', 'authow' ) => 'custom-4',
				esc_html__( 'Custom Style 5', 'authow' ) => 'custom-5'
			),
			'group'      => 'Icon & Image',
			'dependency' => array( 'element' => 'icon_view', 'value_not_equal_to' => 'default' ),
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'icon_width',
			'heading'          => __( 'Width/Height for Box Contain Icon', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'group'            => 'Icon & Image',
			'edit_field_class' => 'vc_col-sm-6',
			'dependency'       => array( 'element' => 'icon_view', 'value_not_equal_to' => 'default' ),
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'icon_padding',
			'heading'          => __( 'Custom Padding for Icon', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'group'            => 'Icon & Image',
			'edit_field_class' => 'vc_col-sm-6',
			'dependency'       => array( 'element' => 'icon_view', 'value_not_equal_to' => 'default' ),
		),
		array(
			'type'        => 'vc_link',
			'heading'     => __( 'URL (Link)', 'authow' ),
			'param_name'  => '_link',
			'description' => __( 'Add link to icon.', 'authow' ),
		),


		// Line
		array(
			'type'             => 'goso_number',
			'param_name'       => 'pline_width',
			'heading'          => __( 'Line width', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'dependency'       => array( 'element' => '_use_line', 'value' => 'true', ),
			'edit_field_class' => 'vc_col-sm-6',
			'group'            => $group_line,
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'pline_height',
			'heading'          => __( 'Line height', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'dependency'       => array( 'element' => '_use_line', 'value' => 'true', ),
			'edit_field_class' => 'vc_col-sm-6',
			'group'            => $group_line,
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'line_margin_top',
			'heading'          => __( 'Margin top', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'dependency'       => array( 'element' => '_use_line', 'value' => 'true', ),
			'edit_field_class' => 'vc_col-sm-6',
			'group'            => $group_line,
		),
		array(
			'type'             => 'goso_number',
			'param_name'       => 'line_margin_bottom',
			'heading'          => __( 'Margin bototm', 'authow' ),
			'value'            => '',
			'std'              => '',
			'suffix'           => 'px',
			'min'              => 1,
			'edit_field_class' => 'vc_col-sm-6',
			'dependency'       => array( 'element' => '_use_line', 'value' => 'true', ),
			'group'            => $group_line,
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Custom color for Line', 'authow' ),
			'param_name'       => 'line_color',
			'group'            => $group_line,
			'edit_field_class' => 'vc_col-sm-6',
		),

		// Typo
		array(
			'type'             => 'textfield',
			'param_name'       => 'ib_typo_heading',
			'heading'          => esc_html__( 'Infor Box', 'authow' ),
			'value'            => '',
			'group'            => $group_color,
			'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Background color', 'authow' ),
			'param_name'       => 'ib_bgcolor',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Borders color', 'authow' ),
			'param_name'       => 'ib_bdcolor',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'       => 'goso_number',
			'param_name' => 'ib_borderwidth',
			'heading'    => __( 'Borders Width', 'authow' ),
			'value'      => '',
			'std'        => '',
			'suffix'     => 'px',
			'min'        => 1,
			'group'      => $group_color,
		),
		array(
			'type'       => 'goso_number',
			'param_name' => 'ib_paddingleft',
			'heading'    => __( 'Padding Left & Right', 'authow' ),
			'value'      => '',
			'std'        => '',
			'suffix'     => 'px',
			'min'        => 1,
			'group'      => $group_color,
		),
		array(
			'type'       => 'goso_number',
			'param_name' => 'ib_paddingtop',
			'heading'    => __( 'Padding Top & Bottom', 'authow' ),
			'value'      => '',
			'std'        => '',
			'suffix'     => 'px',
			'min'        => 1,
			'group'      => $group_color,
		),
		
		array(
			'type'             => 'textfield',
			'param_name'       => 'icon_typo_heading',
			'heading'          => esc_html__( 'Icon', 'authow' ),
			'value'            => '',
			'group'            => $group_color,
			'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Icon color', 'authow' ),
			'param_name'       => 'icon_color',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Icon background color', 'authow' ),
			'param_name'       => 'icon_bgcolor',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Icon border color', 'authow' ),
			'param_name'       => 'icon_border_color',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Icon hover color', 'authow' ),
			'param_name'       => 'icon_hcolor',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Icon hover background color', 'authow' ),
			'param_name'       => 'icon_hbgcolor',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Icon hover border color', 'authow' ),
			'param_name'       => 'icon_hborder_color',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		// Typo title
		array(
			'type'             => 'textfield',
			'param_name'       => 'stitle_typo_heading',
			'heading'          => esc_html__( 'Sub Title', 'authow' ),
			'value'            => '',
			'group'            => $group_color,
			'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Sub Title color', 'authow' ),
			'param_name'       => 'stitle_color',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'       => 'google_fonts',
			'param_name' => '_stitle_typo',
			'value'      => '',
			'group'      => $group_color,
		),
		array(
			'type'       => 'goso_number',
			'param_name' => '_stitle_fsize',
			'heading'    => __( 'Font Size for Sub Title', 'authow' ),
			'value'      => '',
			'std'        => '',
			'suffix'     => 'px',
			'min'        => 1,
			'group'      => $group_color,
		),
		
		array(
			'type'             => 'textfield',
			'param_name'       => 'title_typo_heading',
			'heading'          => esc_html__( 'Title', 'authow' ),
			'value'            => '',
			'group'            => $group_color,
			'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
		),
		array(
			'type'             => 'colorpicker',
			'heading'          => esc_html__( 'Title color', 'authow' ),
			'param_name'       => 'title_color',
			'group'            => $group_color,
			'edit_field_class' => 'vc_col-sm-6',
		),
		array(
			'type'       => 'google_fonts',
			'param_name' => '_title_typo',
			'value'      => '',
			'group'      => $group_color,
		),
		array(
			'type'       => 'goso_number',
			'param_name' => '_title_fsize',
			'heading'    => __( 'Font Size for Title', 'authow' ),
			'value'      => '',
			'std'        => '',
			'suffix'     => 'px',
			'min'        => 1,
			'group'      => $group_color,
		),

		// Content Typography
		array(
			'type'             => 'textfield',
			'param_name'       => '_content_typo_heading',
			'heading'          => esc_html__( 'Content', 'authow' ),
			'value'            => '',
			'group'            => $group_color,
			'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
		),
		array(
			'type'       => 'colorpicker',
			'heading'    => esc_html__( 'Content color', 'authow' ),
			'param_name' => '_content_color',
			'group'      => $group_color,
		),
		array(
			'type'       => 'google_fonts',
			'param_name' => '_content_typo',
			'value'      => '',
			'group'      => $group_color,
		),
		array(
			'type'       => 'goso_number',
			'param_name' => '_content_fsize',
			'heading'    => __( 'Font Size for Content', 'authow' ),
			'value'      => '',
			'std'        => '',
			'suffix'     => 'px',
			'min'        => 1,
			'group'      => $group_color,
		),
		array(
			'type'             => 'textfield',
			'param_name'       => 'extra_options',
			'heading'          => esc_html__( 'Extra Options', 'authow' ),
			'value'            => '',
			'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
		),
		vc_map_add_css_animation(),
		array(
			'type'        => 'textfield',
			'heading'     => esc_html__( 'Extra class name', 'authow' ),
			'param_name'  => 'el_class',
			'description' => esc_html__( 'Style particular content element differently - add a class name and refer to it in custom CSS.', 'authow' ),
		),
		array(
			'type'       => 'css_editor',
			'heading'    => __( 'CSS box', 'authow' ),
			'param_name' => 'css',
			'group'      => __( 'Design Options', 'authow' ),
		)
	)
) );
