<?php
$group_color = 'Typo & Color';

vc_map( array(
    'base'          => 'goso_recent_posts',
    'icon'          => get_template_directory_uri() . '/images/vc-icon.png',
    'category'      => goso_get_theme_name('Authow'),
    'html_template' => get_template_directory() . '/inc/js_composer/shortcodes/recent_posts/frontend.php',
    'weight'        => 700,
    'name'          => goso_get_theme_name('Goso').' '.esc_html__( 'Widget Recent/Popular Posts', 'authow' ),
    'description'   => __( 'Recent Posts Block', 'authow' ),
	'controls'      => 'full',
	'params'        => array_merge(
		array(
            array(
                'type'        => 'loop',
                'heading'     => __( '', 'authow' ),
                'param_name'  => 'build_query',
                'value'       => 'post_type:post|size:10',
                'settings'    => array(
                    'size'      => array( 'value' => 10, 'hidden' => false ),
                    'post_type' => array( 'value' => 'post', 'hidden' => false )
                ),
                'description' => __( 'Create WordPress loop, to populate content from your site.', 'authow' ),
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Custom words length for post titles', 'authow' ),
                'param_name' => 'title_length',
                'description'     => __( 'If your post titles is too long - You can use this option for trim it. Fill number value here.', 'authow' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => __('Image Size Type', 'authow'),
                'value' => array(
                    'Default' => '',
                    'Horizontal Size' => 'horizontal',
                    'Square Size' => 'square',
                    'Vertical Size' => 'vertical',
                    'Custom' => 'custom',
                ),
                'std' => 'horizontal',
                'param_name' => 'goso_size',
            ),
            array(
                'type'             => 'goso_only_number',
                'heading'          => esc_html__( 'Image Ratio.Unit is %. E.g: 50', 'authow' ),
                'param_name'       => 'goso_img_ratio',
                'value'            => '',
                'std'              => '',
                'min'              => 0,
                'max'              => 100,
                'suffix'           => '%',
                'edit_field_class' => 'vc_col-sm-6',
                'dependency' => array( 'element' => 'goso_size', 'value' => 'custom' ),
            ),
			array(
				'type'             => 'dropdown',
				'heading'          => __( 'Custom Image Size', 'authow' ),
				'value'            => array(
					'Default' => '',
					'Thumbnail - 150 x 150' => 'thumbnail',
					'Medium - 300 x 300' => 'medium',
					'Medium Large - 768 x auto' => 'medium_large',
					'Large - 1024 x 1024' => 'large',
					'Goso-single-full - 1920 x auto' => 'goso-single-full',
					'Goso-slider-full-thumb - 1920 x 800' => 'goso-slider-full-thumb',
					'Goso-full-thumb - 1170 x auto' => 'goso-full-thumb',
					'Goso-slider-thumb - 1170 x 663' => 'goso-slider-thumb',
					'Goso-magazine-slider - 780 x 516' => 'goso-magazine-slider',
					'Goso-thumb - 585 x 390' => 'goso-thumb',
					'Goso-masonry-thumb - 585 x auto' => 'goso-masonry-thumb',
					'Goso-thumb-square - 585 x 585' => 'goso-thumb-square',
					'Goso-thumb-vertical - 480 x 650' => 'goso-thumb-vertical',
					'Goso-thumb-small - 263 x 175' => 'goso-thumb-small',
					'Full' => 'full',
				),
				'param_name'       => 'thumb_size',
				'dependency'       => array( 'element' => 'goso_size', 'value' => 'custom' ),
			),
			array(
				'type'             => 'dropdown',
				'heading'          => __( 'Custom Image Size for Featured Posts', 'authow' ),
				'value'            => array(
					'Default'                              => '',
					'Thumbnail - 150 x 150'                => 'thumbnail',
					'Medium - 300 x 300'                   => 'medium',
					'Medium Large - 768 x auto'            => 'medium_large',
					'Large - 1024 x 1024'                  => 'large',
					'Goso-single-full - 1920 x auto'      => 'goso-single-full',
					'Goso-slider-full-thumb - 1920 x 800' => 'goso-slider-full-thumb',
					'Goso-full-thumb - 1170 x auto'       => 'goso-full-thumb',
					'Goso-slider-thumb - 1170 x 663'      => 'goso-slider-thumb',
					'Goso-magazine-slider - 780 x 516'    => 'goso-magazine-slider',
					'Goso-thumb - 585 x 390'              => 'goso-thumb',
					'Goso-masonry-thumb - 585 x auto'     => 'goso-masonry-thumb',
					'Goso-thumb-square - 585 x 585'       => 'goso-thumb-square',
					'Goso-thumb-vertical - 480 x 650'     => 'goso-thumb-vertical',
					'Goso-thumb-small - 263 x 175'        => 'goso-thumb-small',
					'Full'                                 => 'full',
				),
				'param_name'       => 'thumb_bigsize',
				'dependency'       => array( 'element' => 'goso_size', 'value' => 'custom' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Hide thumbnail?', 'authow' ),
				'param_name' => 'hide_thumb',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Display thumbnail on right?', 'authow' ),
				'param_name' => 'thumbright',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'             => 'checkbox',
				'heading'          => esc_html__( 'Display on 2 columns?', 'authow' ),
				'param_name'       => 'twocolumn',
                'description'     => __( 'If you use 2 columns option, it will ignore option display thumbnail on right.', 'authow' ),
                'value'            => array( __( 'Yes', 'authow' ) => 'yes' ),
            ),
            array(
                'type'       => 'checkbox',
                'heading'    => esc_html__( 'Display 1st post featured?', 'authow' ),
                'param_name' => 'featured',
                'value'            => array( __( 'Yes', 'authow' ) => 'yes' ),
            ),
            array(
	            'type'       => 'checkbox',
	            'heading'    => esc_html__( 'Display featured post style 2?', 'authow' ),
	            'param_name' => 'featured2',
	            'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
            ),
			array(
				'type'        => 'checkbox',
				'heading'     => esc_html__( 'Display all post featured?', 'authow' ),
				'param_name'  => 'allfeatured',
				'description' => __( 'If you use all post featured option, it will ignore option display thumbnail on right & 2 columns.', 'authow' ),
				'value'       => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Show author name?', 'authow' ),
				'param_name' => 'show_author',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Hide post date?', 'authow' ),
				'param_name' => 'hide_postdate',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Show Comment Count?', 'authow' ),
				'param_name' => 'show_comment',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Show Post Views?', 'authow' ),
				'param_name' => 'show_postviews',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Enable icon post format?', 'authow' ),
				'param_name' => 'icon_format',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Show the order numbers?', 'authow' ),
				'param_name' => 'ordernum',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'       => 'checkbox',
				'heading'    => esc_html__( 'Hide Border at The Bottom?', 'authow' ),
				'param_name' => 'showborder',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
			),
			array(
				'type'        => 'goso_number',
				'param_name'  => 'imgwidth',
				'heading'     => __( 'Custom Image Width', 'authow' ),
				'description' => __( 'This option doesn\'t apply for featured posts.', 'authow' ),
				'value'       => '',
				'std'         => '',
				'suffix'      => 'px',
				'min'         => 1,
			),
			array(
				'type'       => 'goso_number',
				'param_name' => 'row_gap',
				'heading'    => __( 'Custom Rows Gap Between Post Items', 'authow' ),
				'value'      => '',
				'std'        => '',
				'suffix'     => 'px',
				'min'        => 1,
			),
		),
		Goso_Vc_Params_Helper::heading_block_params(),
		Goso_Vc_Params_Helper::params_heading_typo_color(),
        array(
            array(
                'type'             => 'textfield',
                'param_name'       => 'heading_ptittle_settings',
                'heading'          => esc_html__( 'General Posts', 'authow' ),
                'value'            => '',
                'group'            => $group_color,
                'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
            ),
            array(
                'type'             => 'colorpicker',
                'heading'          => esc_html__( 'Post Border Color', 'authow' ),
                'param_name'       => 'post_border_color',
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            // Post title
            array(
                'type'             => 'colorpicker',
                'heading'          => esc_html__( 'Post Title Color', 'authow' ),
                'param_name'       => 'ptitle_color',
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'             => 'colorpicker',
                'heading'          => esc_html__( 'Post Title Hover Color', 'authow' ),
                'param_name'       => 'ptitle_hcolor',
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'             => 'goso_number',
                'param_name'       => 'ptitle_fsize',
                'heading'          => __( 'Font Size for Post Title', 'authow' ),
                'value'            => '',
                'std'              => '',
                'suffix'           => 'px',
                'min'              => 1,
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'             => 'checkbox',
                'heading'          => __( 'Custom Font Family for Post Title', 'authow' ),
                'param_name'       => 'use_ptitle_typo',
                'value'            => array( __( 'Yes', 'authow' ) => 'yes' ),
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'       => 'google_fonts',
                'group'      => $group_color,
                'param_name' => 'ptitle_typo',
                'value'      => '',
                'dependency' => array( 'element' => 'use_ptitle_typo', 'value' => 'yes' ),
            ),
            array(
                'type'       => 'goso_separator',
                'param_name' => 'goso_separator1',
                'group'      => $group_color,
            ),
            // Post meta
            array(
                'type'             => 'colorpicker',
                'heading'          => esc_html__( 'Post Meta Color', 'authow' ),
                'param_name'       => 'pmeta_color',
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'             => 'goso_number',
                'param_name'       => 'pmeta_fsize',
                'heading'          => __( 'Font Size for Post Meta', 'authow' ),
                'value'            => '',
                'std'              => '',
                'suffix'           => 'px',
                'min'              => 1,
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'             => 'checkbox',
                'heading'          => __( 'Custom Font Family for Post Meta', 'authow' ),
                'param_name'       => 'use_pmeta_typo',
                'value'            => array( __( 'Yes', 'authow' ) => 'yes' ),
                'group'            => $group_color,
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'       => 'google_fonts',
                'group'      => $group_color,
                'param_name' => 'pmeta_typo',
                'value'      => '',
                'dependency' => array( 'element' => 'use_pmeta_typo', 'value' => 'yes' ),
            ),
        ),
		Goso_Vc_Params_Helper::extra_params()
	)
) );
