<?php
$group_color = 'Typo & Color';
$group_team  = 'Team Member';

vc_map( array(
	'base'          => 'goso_team_member',
	'icon'          => get_template_directory_uri() . '/images/vc-icon.png',
	'category'      => goso_get_theme_name('Authow'),
	'html_template' => get_template_directory() . '/inc/js_composer/shortcodes/team_member/frontend.php',
	'weight'        => 700,
	'name'          => goso_get_theme_name('Goso').' '.esc_html__( 'Team Members', 'authow' ),
	'description'   => __( 'Team Members Block', 'authow' ),
	'controls'      => 'full',
	'params'        => array_merge(
		array(
			array(
				'type'       => 'dropdown',
				'heading'    => esc_html__( 'Design style', 'authow' ),
				'param_name' => 'style',
				'std'        => 's1',
				'value'      => array(
					esc_html__( 'Style 1', 'authow' ) => 's1',
					esc_html__( 'Style 2', 'authow' ) => 's2',
					esc_html__( 'Style 3', 'authow' ) => 's3',
					esc_html__( 'Style 4', 'authow' ) => 's4',
				)
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Columns', 'authow' ),
				'param_name' => 'columns',
				'value'      => array(
					'1' => '1',
					'2' => '2',
					'3' => '3',
					'4' => '4',
					'5' => '5',
					'6' => '6',
				),
				'std'        => '3'
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'height_team',
				'heading'          => esc_html__( 'Set height team member', 'authow' ),
				'value'            => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'border_width_team',
				'heading'          => esc_html__( 'Set border width team member', 'authow' ),
				'value'            => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'width_img',
				'heading'          => esc_html__( 'Set width for Image', 'authow' ),
				'value'            => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'height_img',
				'heading'          => esc_html__( 'Set height for Image', 'authow' ),
				'value'            => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'row_gap',
				'heading'          => __( 'Rows Gap', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'col_gap',
				'heading'          => __( 'Columns Gap', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),

			// tab team members
			array(
				'type'       => 'param_group',
				'heading'    => '',
				'param_name' => 'teammembers',
				'group'      => $group_team,
				'value'      => urlencode( json_encode( array(
					array(
						'name'          => 'Team member 1',
						'desc'          => 'I am text block. Click edit button to change this text.',
						'link'          => __( 'https://your-link.com', 'authow' ),
						'image'         => '',
						'link_website'  => '#',
						'link_facebook' => '#',
						'link_twitter'  => '#'
					),
					array(
						'name'          => 'Team member 2',
						'desc'          => 'I am text block. Click edit button to change this text.',
						'link'          => __( 'https://your-link.com', 'authow' ),
						'image'         => '',
						'link_website'  => '#',
						'link_facebook' => '#',
						'link_twitter'  => '#'
					),
					array(
						'name'          => 'Team member 3',
						'desc'          => 'I am text block. Click edit button to change this text.',
						'link'          => __( 'https://your-link.com', 'authow' ),
						'image'         => '',
						'link_website'  => '#',
						'link_facebook' => '#',
						'link_twitter'  => '#'
					),
				) ) ),
				'params'     => array(
					array(
						'type'        => 'attach_image',
						'heading'     => __( 'Image', 'authow' ),
						'param_name'  => 'image',
						'value'       => '',
						'description' => __( 'Select image from media library.', 'authow' ),
					),
					array(
						'type'        => 'textfield',
						'heading'     => __( 'Name', 'authow' ),
						'param_name'  => 'name',
						'admin_label' => true,
					),
					array(
						'type'       => 'textfield',
						'heading'    => __( 'Position', 'authow' ),
						'param_name' => 'position',
					),
					array(
						'type'       => 'textarea',
						'heading'    => __( 'Description', 'authow' ),
						'param_name' => 'desc',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Website', 'authow' ),
						'param_name'       => 'link_website',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Facebook', 'authow' ),
						'param_name'       => 'link_facebook',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Twitter', 'authow' ),
						'param_name'       => 'link_twitter',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Linkedin', 'authow' ),
						'param_name'       => 'link_linkedin',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Instagram', 'authow' ),
						'param_name'       => 'link_instagram',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Youtube', 'authow' ),
						'param_name'       => 'link_youtube',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Vimeo', 'authow' ),
						'param_name'       => 'link_vimeo',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Pinterest', 'authow' ),
						'param_name'       => 'link_pinterest',
						'edit_field_class' => 'vc_col-sm-6',
					),
					array(
						'type'             => 'textfield',
						'heading'          => __( 'Link Dribbble', 'authow' ),
						'param_name'       => 'link_dribbble',
						'edit_field_class' => 'vc_col-sm-6',
					),
				),
			),
		),
		Goso_Vc_Params_Helper::heading_block_params(),
		Goso_Vc_Params_Helper::params_heading_typo_color(),
		array(
			// General typo
			array(
				'type'             => 'textfield',
				'param_name'       => 'heading_general_settings',
				'heading'          => esc_html__( 'Team memeber Colors', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Item Background Color', 'authow' ),
				'param_name'       => 'team_bghcolor',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Item Border Color', 'authow' ),
				'param_name'       => 'team_borderhcolor',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			// Name typo
			array(
				'type'             => 'textfield',
				'param_name'       => 'heading_name_settings',
				'heading'          => esc_html__( 'Name Colors', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Name color', 'authow' ),
				'param_name'       => 'team_name_color',
				'group'            => $group_color,
			),
			array(
				'type'             => 'google_fonts',
				'param_name'       => 'team_name_typo',
				'value'            => '',
				'group'            => $group_color,
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'team_name_size',
				'heading'          => __( 'Font Size for Name', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'group'            => $group_color,
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'team_name_martop',
				'heading'          => __( 'Margin top for Name', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),

			// Position typo
			array(
				'type'             => 'textfield',
				'param_name'       => 'heading_pos_settings',
				'heading'          => esc_html__( 'Positions Colors', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Position color', 'authow' ),
				'param_name'       => 'team_pos_color',
				'group'            => $group_color,
			),
			array(
				'type'             => 'google_fonts',
				'param_name'       => 'team_pos_typo',
				'value'            => '',
				'group'            => $group_color,
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'team_pos_size',
				'heading'          => __( 'Font Size for Position', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'group'            => $group_color,
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'team_pos_martop',
				'heading'          => __( 'Margin top for Position', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),

			// Description typo
			array(
				'type'             => 'textfield',
				'param_name'       => 'heading_des_settings',
				'heading'          => esc_html__( 'Description colors', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Desctiption color', 'authow' ),
				'param_name'       => 'team_des_color',
				'group'            => $group_color,
			),
			array(
				'type'             => 'google_fonts',
				'param_name'       => 'team_des_typo',
				'value'            => '',
				'group'            => $group_color,
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'team_des_size',
				'heading'          => __( 'Font Size for Desctiption', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'team_des_martop',
				'heading'          => __( 'Margin top for Desctiption', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),

			// Social typo
			array(
				'type'             => 'textfield',
				'param_name'       => 'heading_social_settings',
				'heading'          => esc_html__( 'Social Icon Colors', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Social Icon Color', 'authow' ),
				'param_name'       => 'team_social_color',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Social Icon Background Color', 'authow' ),
				'param_name'       => 'team_social_bgcolor',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Social Icon Hover Color', 'authow' ),
				'param_name'       => 'team_social_hcolor',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Social Icon Background Hover Color', 'authow' ),
				'param_name'       => 'team_social_bghcolor',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'       => 'goso_number',
				'param_name' => 'team_social_martop',
				'heading'    => __( 'Margin top for Social Icon', 'authow' ),
				'value'      => '',
				'std'        => '',
				'suffix'     => 'px',
				'min'        => 1,
				'group'      => $group_color,
			),
		),
		Goso_Vc_Params_Helper::extra_params()
	)
) );
