<?php
$group_color = 'Typo & Color';

vc_map( array(
	'base'          => 'goso_counter_up',
	'icon'          => get_template_directory_uri() . '/images/vc-icon.png',
	'category'      => goso_get_theme_name('Authow'),
	'html_template' => get_template_directory() . '/inc/js_composer/shortcodes/counter_up/frontend.php',
	'weight'        => 700,
	'name'          => goso_get_theme_name('Goso').' '.esc_html__( 'Counter Up', 'authow' ),
	'description'   => __( 'Counter Up Block', 'authow' ),
	'controls'      => 'full',
	'params'        => array_merge(
		Goso_Vc_Params_Helper::params_container_width(),
		array(
			array(
				'type'       => 'dropdown',
				'heading'    => esc_html__( 'Counter Up style', 'authow' ),
				'param_name' => 'cup_style',
				'std'        => 's1',
				'value'      => array(
					esc_html__( 'Style 1', 'authow' ) => 's1',
					esc_html__( 'Style 2', 'authow' ) => 's2',
				),
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Posttion', 'authow' ),
				'param_name' => 'cup_align',
				'value'      => array(
					__( 'Align Center', 'authow' ) => 'center',
					__( 'Align Left', 'authow' )   => 'left',
					__( 'Align Right', 'authow' )  => 'right',
				),
				'std'        => 'center',
				'dependency' => array( 'element' => 'cup_style', 'value' => 's1' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => esc_html__( 'Number', 'authow' ),
				'param_name' => 'cup_number'
			),
			array(
				'type'       => 'textfield',
				'heading'    => esc_html__( 'Prefix of number', 'authow' ),
				'param_name' => 'cup_prefix_number'
			),
			array(
				'type'       => 'textfield',
				'heading'    => esc_html__( 'Suffix of number', 'authow' ),
				'param_name' => 'cup_suffix_number',
			),
			array(
				'type'        => 'textfield',
				'heading'     => esc_html__( 'Title', 'authow' ),
				'param_name'  => 'cup_title',
				'admin_label' => true
			),
			array(
				'type'       => 'dropdown',
				'heading'    => esc_html__( 'Icon type', 'authow' ),
				'param_name' => 'cup_icon_type',
				'value'      => array(
					esc_html__( 'Icon', 'authow' )  => 'icon',
					esc_html__( 'Image', 'authow' ) => 'image',
				),
			),
			array(
				'type'       => 'attach_image',
				'heading'    => esc_html__( 'Image', 'authow' ),
				'param_name' => 'cup_image',
				'dependency' => array( 'element' => 'cup_icon_type', 'value' => 'image' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Image size', 'authow' ),
				'param_name' => 'img_size',
				'std'        => 'full',
				'dependency' => array( 'element' => 'cup_icon_type', 'value' => 'image' ),
			),
			array(
				'type'       => 'iconpicker',
				'heading'    => __( 'Icon', 'authow' ),
				'param_name' => 'cup_icon',
				'value'      => '',
				'settings'   => array( 'emptyIcon' => true, 'iconsPerPage' => 4000 ),
				'dependency' => array( 'element' => 'cup_icon_type', 'value' => 'icon' )
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Icon Border Style', 'authow' ),
				'param_name' => 'icon_border_style',
				'value'      => array(
					esc_html__( 'None', 'authow' )   => '',
					esc_html__( 'Solid', 'authow' )  => 'solid',
					esc_html__( 'Dashed', 'authow' ) => 'dashed',
					esc_html__( 'Dotted', 'authow' ) => 'dotted',
					esc_html__( 'Double', 'authow' ) => 'double',
				),
				'dependency' => array( 'element' => 'cup_icon_type', 'value' => 'icon' ),
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'icon_border_width',
				'heading'          => __( 'Border width for Icon', 'authow' ),
				'value'            => '1',
				'std'              => '1',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
				'dependency'       => array( 'element' => 'icon_border_style', 'value' => array( 'solid', 'dashed', 'dotted', 'double' ) ),
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'icon_border_radius',
				'heading'          => __( 'Border radius for Icon', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
				'dependency'       => array( 'element' => 'icon_border_style', 'value' => array( 'solid', 'dashed', 'dotted', 'double' ) ),
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'icon_padding',
				'heading'          => __( 'Padding for Icon', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
				'dependency'       => array( 'element' => 'icon_size', 'value' => 'custom' ),
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => '_image_width_height',
				'heading'          => __( 'Image with/height', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
				'dependency'       => array( 'element' => 'cup_icon_type', 'value' => 'image' ),
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'icon_margin_bottom',
				'heading'          => __( 'Custom margin bottom for Icon or Image', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'number_margin_top',
				'heading'          => __( 'Custom margin top for number', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'number_padding_lr',
				'heading'          => __( 'Custom padding left/right for number', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'title_margin_top',
				'heading'          => __( 'Custom margin top for title', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'       => 'textfield',
				'heading'    => esc_html__( 'Delay', 'authow' ),
				'param_name' => 'cup_delay',
			),
			array(
				'type'       => 'textfield',
				'heading'    => esc_html__( 'Time', 'authow' ),
				'param_name' => 'cup_time',
			),
			// Heading
			array(
				'type'       => 'checkbox',
				'heading'    => __( 'Show Heading Title', 'authow' ),
				'param_name' => 'show_block_heading',
				'value'      => array( __( 'Yes', 'authow' ) => 'yes' ),
				'group'      => 'Heading',
			),
			array(
				'type'       => 'dropdown',
				'heading'    => esc_html__( 'Heading Title Style', 'authow' ),
				'param_name' => 'heading_title_style',
				'std'        => '',
				'value'      => array(
					esc_html__( 'Default ( follow Customize )', 'authow' ) => '',
					esc_html__( 'Style 1', 'authow' )                      => 'style-1',
					esc_html__( 'Style 2', 'authow' )                      => 'style-2',
					esc_html__( 'Style 3', 'authow' )                      => 'style-3',
					esc_html__( 'Style 4', 'authow' )                      => 'style-4',
					esc_html__( 'Style 5', 'authow' )                      => 'style-5',
					esc_html__( 'Style 6', 'authow' )                      => 'style-6',
					esc_html__( 'Style 7', 'authow' )                      => 'style-7',
					esc_html__( 'Style 8', 'authow' )                      => 'style-9',
					esc_html__( 'Style 9', 'authow' )                      => 'style-8',
					esc_html__( 'Style 10', 'authow' )                     => 'style-10',
					esc_html__( 'Style 11', 'authow' )                     => 'style-11',
					esc_html__( 'Style 12', 'authow' )                     => 'style-12',
					esc_html__( 'Style 13', 'authow' )                     => 'style-13',
					esc_html__( 'Style 14', 'authow' )                     => 'style-14',
					esc_html__( 'Style 15', 'authow' )                     => 'style-15',
					esc_html__( 'Style 16', 'authow' )                     => 'style-16',
					esc_html__( 'Style 17', 'authow' )                     => 'style-2 style-17',
					esc_html__( 'Style 18', 'authow' )                     => 'style-18',
					esc_html__( 'Style 19', 'authow' )                     => 'style-18 style-19',
					esc_html__( 'Style 20', 'authow' )                     => 'style-18 style-20',
				),
				'group'      => 'Heading',
			),
			array(
				'type'        => 'textfield',
				'heading'     => esc_html__( 'Heading Title', 'authow' ),
				'param_name'  => 'heading',
				'value'       => esc_html__( 'Heading Title', 'authow' ),
				'std'         => esc_html__( 'Heading Title', 'authow' ),
				'admin_label' => true,
				'description' => esc_html__( 'A title for this block, if you leave it blank the block will not have a title', 'authow' ),
				'group'       => 'Heading',
			),
			array(
				'type'        => 'textfield',
				'heading'     => esc_html__( 'Title Url', 'authow' ),
				'param_name'  => 'heading_title_link',
				'std'         => '',
				'description' => esc_html__( 'A custom url when the block title is clicked', 'authow' ),
				'group'       => 'Heading',
			),
			array(
				'type'       => 'dropdown',
				'heading'    => esc_html__( 'Heading Align', 'authow' ),
				'param_name' => 'heading_title_align',
				'std'        => '',
				'value'      => array(
					esc_html__( 'Default ( follow Customize )', 'authow' ) => '',
					esc_html__( 'Left', 'authow' )                         => 'pcalign-left',
					esc_html__( 'Center', 'authow' )                       => 'pcalign-center',
					esc_html__( 'Right', 'authow' )                        => 'pcalign-right',
				),
				'group'      => 'Heading',
			),
			array(
				'type'        => 'dropdown',
				'heading'     => 'Align Icon on Style 15',
				'value'       => array(
					'Default( follow Customize )' => '',
					'Right'                       => 'pciconp-right',
					'Left'                        => 'pciconp-left',
				),
				'param_name'  => 'heading_icon_pos',
				'description' => '',
				'dependency'  => array( 'element' => 'heading_title_style', 'value' => array( 'style-15' ) ),
				'group'       => 'Heading',
			),
			array(
				'type'        => 'dropdown',
				'heading'     => 'Custom Icon on Style 15',
				'value'       => array(
					'Default( follow Customize )' => '',
					'Arrow Right'                 => 'pcicon-right',
					'Arrow Left'                  => 'pcicon-left',
					'Arrow Down'                  => 'pcicon-down',
					'Arrow Up'                    => 'pcicon-up',
					'Star'                        => 'pcicon-star',
					'Bars'                        => 'pcicon-bars',
					'File'                        => 'pcicon-file',
					'Fire'                        => 'pcicon-fire',
					'Book'                        => 'pcicon-book',
				),
				'param_name'  => 'heading_icon',
				'description' => '',
				'dependency'  => array( 'element' => 'heading_title_style', 'value' => array( 'style-15' ) ),
				'group'       => 'Heading',
			),
		),
		Goso_Vc_Params_Helper::params_heading_typo_color(),
		// Color
		array(
			array(
				'type'             => 'textfield',
				'param_name'       => 'cup_icon_heading',
				'heading'          => esc_html__( 'Icon', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Icon color', 'authow' ),
				'param_name'       => 'cup_icon_color',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Icon background color', 'authow' ),
				'param_name'       => 'cup_icon_bgcolor',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'cup_icon_size',
				'heading'          => __( 'Font size for Icon', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
				'group'            => $group_color,
			),
			array(
				'type'             => 'textfield',
				'param_name'       => 'cup_number_heading',
				'heading'          => esc_html__( 'Number', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Number Color', 'authow' ),
				'param_name'       => 'cup_number_color',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'       => 'google_fonts',
				'group'      => $group_color,
				'param_name' => 'cup_number_typo',
				'value'      => '',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'cup_number_size',
				'heading'          => __( 'Font Size for Number', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
				'group'            => $group_color,
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Font Weight for Number', 'authow' ),
				'param_name' => 'cup_number_weight',
				'std'        => 's1',
				'value'      => array(
					__( 'Default', 'authow' ) => '',
					'Normal'                   => 'normal',
					'Bold'                     => 'bold',
					'Bolder'                   => 'bolder',
					'Lighter'                  => 'lighter',
					'100'                      => '100',
					'200'                      => '200',
					'300'                      => '300',
					'400'                      => '400',
					'500'                      => '500',
					'600'                      => '600',
					'700'                      => '700',
					'800'                      => '800',
					'900'                      => '900'
				),
				'group'      => $group_color,
			),
			array(
				'type'             => 'textfield',
				'param_name'       => 'cup_prefix_suffix_heading',
				'heading'          => esc_html__( 'Prefix and Suffix', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Prefix and Suffix Color', 'authow' ),
				'param_name'       => 'cup_frefix_color',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'       => 'google_fonts',
				'group'      => $group_color,
				'param_name' => 'cup_frefix_typo',
				'value'      => '',
			),
			array(
				'type'             => 'goso_number',
				'heading'          => esc_html__( 'Font size for Prefix and Suffix', 'authow' ),
				'param_name'       => 'cup_frefix_size',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'             => 'textfield',
				'param_name'       => 'cup_title_heading',
				'heading'          => esc_html__( 'Title', 'authow' ),
				'value'            => '',
				'group'            => $group_color,
				'edit_field_class' => 'goso-param-heading-wrapper no-top-margin vc_column vc_col-sm-12',
			),
			array(
				'type'             => 'colorpicker',
				'heading'          => esc_html__( 'Title color', 'authow' ),
				'param_name'       => 'cup_title_color',
				'group'            => $group_color,
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type'       => 'google_fonts',
				'group'      => $group_color,
				'param_name' => 'cup_title_typo',
				'value'      => '',
			),
			array(
				'type'             => 'goso_number',
				'param_name'       => 'cup_title_size',
				'heading'          => __( 'Font size for Title', 'authow' ),
				'value'            => '',
				'std'              => '',
				'suffix'           => 'px',
				'min'              => 1,
				'edit_field_class' => 'vc_col-sm-6',
				'group'            => $group_color,
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Font Weight for Number', 'authow' ),
				'param_name' => 'cup_title_weight',
				'std'        => 's1',
				'value'      => array(
					__( 'Default', 'authow' ) => '',
					'Normal'                   => 'normal',
					'Bold'                     => 'bold',
					'Bolder'                   => 'bolder',
					'Lighter'                  => 'lighter',
					'100'                      => '100',
					'200'                      => '200',
					'300'                      => '300',
					'400'                      => '400',
					'500'                      => '500',
					'600'                      => '600',
					'700'                      => '700',
					'800'                      => '800',
					'900'                      => '900'
				),
				'group'      => $group_color,
			),
		),
		Goso_Vc_Params_Helper::extra_params()
	)
) );
